"""Initial migration

Revision ID: 03bfdff1c6a3
Revises:
Create Date: 2021-08-05 21:02:42.599625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bfdff1c6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vk_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_group')
    op.drop_table('user')
    # ### end Alembic commands ###
