"""Nullable fields

Revision ID: 1bf0a68000f7
Revises: a00580ee07f6
Create Date: 2021-08-05 23:24:37.326795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf0a68000f7'
down_revision = 'a00580ee07f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
