"""New column

Revision ID: 6fc8b2d870f1
Revises: ac17695451f0
Create Date: 2021-07-25 11:38:30.150069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc8b2d870f1'
down_revision = 'ac17695451f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('a', sa.Column('data2', sa.String(), server_default='Smth', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('a', 'data2')
    # ### end Alembic commands ###
