"""Nullable fields

Revision ID: a00580ee07f6
Revises: b16b66c1c461
Create Date: 2021-08-05 23:24:00.034833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00580ee07f6'
down_revision = 'b16b66c1c461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
